In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import scipy.stats
import math
from sklearn.model_selection import train_test_split
from sklearn import metrics
from hklearn.naive_bayes import BernoulliNB, MultinomialNB

### Nota general: En este ejercicio se implementó Naive Bayes para las distribuciones de Bernoulli y multinomial tanto con estimadores EMV y MAP, ambas implementaciones se están importando desde el módulo hklearn.naive_bayes que se creó, para ver las implementaciones basta con ir al archivo hklearn/naive_bayes.py

## Comenzamos cargando el dataframe de los correos spam.csv

In [2]:
df = pd.read_table('spam.csv')

## Observamos que los datos vienen en una sola columna, así que los preprocesamos

In [3]:
df

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

### Los datos de cada renglón vienen en una cadena, donde cada dato de cada columna viene separado por un espacio, por lo tanto utilizamos una separación simple de la cadena en una lista y reasignamos al renglón el conjunto de valores de cada columna

In [4]:
def toFloat(x):
    try:
        return float(x)
    except:
        print(x)
        return 0.
n = len(str(list(df.iloc[0])).split())
m = df.shape[1]
df_processed = pd.DataFrame(np.zeros((m,n)))
for i in range(df.shape[0]):
    a = str(list(df.iloc[i])).split()
    a[0] = a[0].lstrip("['")
    a[-1] = a[-1].rstrip("]'")
    li = list(map(toFloat, a))
    df_processed.at[i, :] = np.array(li)

In [5]:
df_processed

0     1     2     3     4     5     6     7     8     9     ...  1991  \
0      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      3.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0   0.0   7.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5166   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0  ...   0.0   
5167   0.0   0.0   0.0   0.0   3.0   4.0   0.0   0.0   0.0   0.0  ...   0.0   
5168   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   1.0   0.0  ...   0.0   
5169   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
5170   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0   4.0   0.0  ...   0.0   

      1992  1993  1994  1995  1996  1997  1998  1999  2000  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  
2      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
5166   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5167   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5168   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5169   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5170   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5171 rows x 2001 columns]

### Guardamos los datos procesados en otro archivo csv para cargarlos posteriormente de manera directa

In [6]:
df_processed.to_csv("spam_processed.csv")

In [7]:
df = pd.read_csv("spam_processed.csv")

In [8]:
df = df.drop(axis = 1, labels = ['Unnamed: 0'])

In [9]:
df

0    1    2    3    4    5    6    7    8    9  ...  1991  1992  1993  \
0     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
1     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   1.0   0.0   
3     1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
4     3.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  7.0  ...   0.0   0.0   0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
5166  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.0  0.0  ...   0.0   0.0   0.0   
5167  0.0  0.0  0.0  0.0  3.0  4.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
5168  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...   0.0   0.0   0.0   
5169  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   
5170  0.0  0.0  0.0  0.0  4.0  0.0  0.0  0.0  4.0  0.0  ...   0.0   0.0   0.0   

      1994  1995  1996  1997  1998  1999  2000  
0      0.0   0.0   0.0   0.0   0.0   1.0   1.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   1.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   1.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   1.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   1.0  
...    ...   ...   ...   ...   ...   ...   ...  
5166   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5167   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5168   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5169   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
5170   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5171 rows x 2001 columns]

### Porcentajes de correos spam y no spam

In [10]:
print("Porcentaje etiquetado como spam: " + str(100. * df[df['2000'] == 1.0].shape[0]/df.shape[0]))
print("Porcentaje etiquetado como no spam: " + str(100. * df[df['2000'] == 0.0].shape[0]/df.shape[0]))

Porcentaje etiquetado como spam: 28.988590214658675
Porcentaje etiquetado como no spam: 71.01140978534133


### Dividiendo aleatoriamente el conjunto de datos en entrenamiento, validación y prueba

In [11]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=0)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=0)

### Comenzaremos haciendo uso de un modelo bayesiano ingenuo, asumiendo una distribución de bernoulli tanto para las clases como para los atributos. Este modelo fue programado para esta tarea y es parte del módulo hklearn (homekitlearn) el cual se irá construyendo a lo largo de las tareas para esta clase.
#### Al utilizar Bernoulli para el caso de los atributos, se tendrá que las $n$ ocurrencias de cada palabra correspondiente a cada atributo, se reduciran a si hubo o no ocurrencia.

#### Hacemos uso del estimador máximo a posteriori con una $\alpha = 2$ para entrenar nuestro modelo BernoulliNB y hacemos las predicciones correspondientes al conjunto de entrenamiento y prueba.

In [12]:
model = BernoulliNB(estimator='MAP', alpha = 2.0)
model.fit(X_train, y_train)
y_pred_train = model.predict(X_train) 
print(y_pred_train)
print(f"Reporte de clasificación para el clasificador casero BernoulliNB (maximo a posteriori) en los datos de entrenamiento:\n"
      f"{metrics.classification_report(y_train, y_pred_train)}\n")
y_pred_val = model.predict(X_val) 
print(y_pred_val)
print(f"Reporte de clasificación para el clasificador casero BernoulliNB (maximo a posteriori) en los datos de validación:\n"
      f"{metrics.classification_report(y_val, y_pred_val)}\n")

[1 1 0 ... 0 0 0]
Reporte de clasificación para el clasificador casero BernoulliNB (maximo a posteriori) en los datos de entrenamiento:
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98      2211
         1.0       0.91      0.99      0.95       891

    accuracy                           0.97      3102
   macro avg       0.95      0.97      0.96      3102
weighted avg       0.97      0.97      0.97      3102


[1 1 0 ... 0 0 0]
Reporte de clasificación para el clasificador casero BernoulliNB (maximo a posteriori) en los datos de validación:
              precision    recall  f1-score   support

         0.0       0.99      0.96      0.98       740
         1.0       0.91      0.98      0.95       294

    accuracy                           0.97      1034
   macro avg       0.95      0.97      0.96      1034
weighted avg       0.97      0.97      0.97      1034




#### Hacemos uso del estimador de máxima verosimilitud para entrenar nuestro modelo BernoulliNB y hacemos las predicciones correspondientes al conjunto de entrenamiento y prueba.

In [13]:
model2 = BernoulliNB(estimator='ML')
model2.fit(X_train, y_train)
y_pred_train = model2.predict(X_train) 
print(y_pred_train)
print(f"Reporte de clasificación para el clasificador casero BernoulliNB (maxima verosimilitud) en los datos de entrenamiento:\n"
      f"{metrics.classification_report(y_train, y_pred_train)}\n")
y_pred_val = model2.predict(X_val) 
print(y_pred_val)
print(f"Reporte de clasificación para el clasificador casero BernoulliNB (maxima verosimilitud) en los datos de validación::\n"
      f"{metrics.classification_report(y_val, y_pred_val)}\n")

[0 0 0 ... 0 0 0]
Reporte de clasificación para el clasificador casero BernoulliNB (maxima verosimilitud) en los datos de entrenamiento:
              precision    recall  f1-score   support

         0.0       0.95      0.96      0.96      2211
         1.0       0.91      0.89      0.90       891

    accuracy                           0.94      3102
   macro avg       0.93      0.92      0.93      3102
weighted avg       0.94      0.94      0.94      3102


[1 0 0 ... 0 0 0]
Reporte de clasificación para el clasificador casero BernoulliNB (maxima verosimilitud) en los datos de validación::
              precision    recall  f1-score   support

         0.0       0.93      0.97      0.95       740
         1.0       0.92      0.82      0.87       294

    accuracy                           0.93      1034
   macro avg       0.92      0.90      0.91      1034
weighted avg       0.93      0.93      0.93      1034




#### Para el caso de Bernoulli con el estimador MAP, se tuvo un rendimiento mayor en términos de precisión de las predicciones con respecto al EMV, de hecho este modelo fue el que tuvo un mayor rendimiento, pese a la pérdida de información derivada de asumir cada variable como binaria.

### Para el segundo modelo vamos a asumir una distribución multinomial tanto para las clases como para los atributos. Esta distribución se asume porque cada atributo de cada ejemplo toma valores enteros que son las ocurrencias de palabras, cada ejemplo se puede ver como un vector aleatorio $\mathbf{x} = (x_1, ..., x_{K})$, donde $x_j$ es el número de ocurrencias de la palabra j-esima.

#### Hacemos uso del estimador máximo a posteriori con una $\alpha = 2$ y una $\beta$ correspondiente al número de clases para los estimadores de la clase, y al número de atributos para los estimadores de los atributos dada la clase, para entrenar nuestro modelo MultinomialNB y hacemos las predicciones correspondientes al conjunto de entrenamiento y prueba.

In [14]:
model3 = MultinomialNB(estimator='MAP', alpha = 2.0)
model3.fit(X_train, y_train)
y_pred_train = model3.predict(X_train) 
print(y_pred_train)
print(f"Reporte de clasificación para el clasificador casero MultinomialNB (maximo a posteriori) en los datos de entrenamiento:\n"
      f"{metrics.classification_report(y_train, y_pred_train)}\n")
y_pred_val = model3.predict(X_val) 
print(y_pred_val)
print(f"Reporte de clasificación para el clasificador casero MultinomialNB (maximo a posteriori) en los datos de validación:\n"
      f"{metrics.classification_report(y_val, y_pred_val)}\n")

[1 0 0 ... 0 0 0]
Reporte de clasificación para el clasificador casero MultinomialNB (maximo a posteriori) en los datos de entrenamiento:
              precision    recall  f1-score   support

         0.0       0.98      0.95      0.97      2211
         1.0       0.89      0.95      0.92       891

    accuracy                           0.95      3102
   macro avg       0.94      0.95      0.94      3102
weighted avg       0.95      0.95      0.95      3102


[1 1 0 ... 0 0 0]
Reporte de clasificación para el clasificador casero MultinomialNB (maximo a posteriori) en los datos de validación:
              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97       740
         1.0       0.93      0.92      0.92       294

    accuracy                           0.96      1034
   macro avg       0.95      0.95      0.95      1034
weighted avg       0.96      0.96      0.96      1034




#### Hacemos uso del estimador de máxima verosimilitud para entrenar nuestro modelo MultinomialNB y hacemos las predicciones correspondientes al conjunto de entrenamiento y prueba.

In [15]:
model4 = MultinomialNB(estimator='ML')
model4.fit(X_train, y_train)
y_pred_train = model4.predict(X_train) 
print(y_pred_train)
print(f"Reporte de clasificación para el clasificador casero MultinomialNB (maxima verosimilitud) en los datos de entrenamiento:\n"
      f"{metrics.classification_report(y_train, y_pred_train)}\n")
y_pred_val = model4.predict(X_val) 
print(y_pred_val)
print(f"Reporte de clasificación para el clasificador casero MultinomialNB (maxima verosimilitud) en los datos de validación:\n"
      f"{metrics.classification_report(y_val, y_pred_val)}\n")

[1 0 0 ... 0 0 0]
Reporte de clasificación para el clasificador casero MultinomialNB (maxima verosimilitud) en los datos de entrenamiento:
              precision    recall  f1-score   support

         0.0       0.98      0.96      0.97      2211
         1.0       0.91      0.95      0.93       891

    accuracy                           0.96      3102
   macro avg       0.95      0.96      0.95      3102
weighted avg       0.96      0.96      0.96      3102


[1 1 0 ... 0 0 0]
Reporte de clasificación para el clasificador casero MultinomialNB (maxima verosimilitud) en los datos de validación:
              precision    recall  f1-score   support

         0.0       0.97      0.97      0.97       740
         1.0       0.93      0.92      0.93       294

    accuracy                           0.96      1034
   macro avg       0.95      0.95      0.95      1034
weighted avg       0.96      0.96      0.96      1034




In [16]:
y_pred_test = model.predict(X_test) 
print(y_pred_test)
print(f"Reporte de clasificación para el clasificador casero BernoulliNB (maximo a posteriori) en los datos de prueba:\n"
      f"{metrics.classification_report(y_test, y_pred_test)}\n")

[0 0 0 ... 1 0 0]
Reporte de clasificación para el clasificador casero BernoulliNB (maximo a posteriori) en los datos de prueba:
              precision    recall  f1-score   support

         0.0       1.00      0.96      0.98       721
         1.0       0.92      0.99      0.95       314

    accuracy                           0.97      1035
   macro avg       0.96      0.98      0.97      1035
weighted avg       0.97      0.97      0.97      1035


